import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SelvanPage Page",
  description: "This is a sample page generated by generator",
};

export default function SelvanPage() {
  return (
    <main className="p-6">
      <h1>Hello from SelvanPage 👋</h1>
      <p>This page uses App Router metadata for SOss.</p>
    </main>
  );
}