import { Metadata } from "next";

export const metadata: Metadata = {
  title: "JadshanPage Page",
  description: "This is a sample page generated by generator",
};

export default function JadshanPage() {
  return (
    <main className="p-6">
      <h1>Hello from JadshanPage 👋</h1>
      <p>This page uses App Router metadata for SE.</p>
    </main>
  );
}